apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: petclinic
  description: Spring Pet Clinic
  tags:
    - tanzu
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=petclinic'
spec:
  type: service
  lifecycle: experimental
  owner: default-team
