apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: server
    app.kubernetes.io/part-of: petclinic
spec:
  image: dsyer/petclinic
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: mysql
  - name: SPRING_APPLICATION_JSON
    value: '{"logging.level.org.springframework.web":"trace"}'
  params:
  - name: debug
    value: "true"
  serviceClaims:
  - name: secret
    ref:
      apiVersion: v1
      kind: Secret
      name: demo-db