apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: petclinic
spec:
  image: dsyer/petclinic
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: mysql
  serviceClaims:
  - name: secret
    ref:
      apiVersion: v1
      kind: Secret
      name: spring-petclinic-db