apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: petclinic
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: petclinic
    apps.tanzu.vmware.com/has-tests: "true"
spec:
  source:
    image: index.dockerhub.io/dsyer/petclinic
  env:
  - name: SPRING_PROFILES_ACTIVE
    value: mysql
  build:
    env:
      - name: BP_JVM_VERSION
        value: "17"
      - name: BP_GRADLE_BUILD_FILE
        value: nosuchfile.gradle
  serviceClaims:
  - name: secret
    ref:
      apiVersion: v1
      kind: Secret
      name: spring-petclinic-db